<a href="https://colab.research.google.com/github/crixtiam/gt06/blob/main/EDA_gt05_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

Le asignamos a data un dataframe de datos

In [ ]:
data = pd.read_json('/content/valorant_data.json')

data.head()

,playerName,team,rating,region,playerStatistics,agent,playerCategory
0,Kouf,AMB,1.53,Americas,"{'average_combat_score': '298.0', 'kill_deaths...","[reyna, kayo]",vct-challengers
1,nelu,63,1.31,Americas,"{'average_combat_score': '266.7', 'kill_deaths...","[viper, sova, breach]",vct-challengers
2,welyy,Blue,1.31,Americas,"{'average_combat_score': '240.9', 'kill_deaths...","[sova, fade, breach]",vct-challengers
3,ShoT_UP,TOR,1.29,Americas,"{'average_combat_score': '240.2', 'kill_deaths...","[skye, astra, killjoy]",vct-challengers
4,mada,NRG,1.26,Americas,"{'average_combat_score': '268.8', 'kill_deaths...","[raze, jett, reyna]",vct-challengers

2. saber que columnas tenemos

In [ ]:
data.columns

Index(['playerName', 'team', 'rating', 'region', 'playerStatistics', 'agent',
       'playerCategory'],
      dtype='object')

3. información del tipo de datos

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2054 entries, 0 to 2053
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   playerName        2054 non-null   object
 1   team              2054 non-null   object
 2   rating            2054 non-null   object
 3   region            2054 non-null   object
 4   playerStatistics  2054 non-null   object
 5   agent             2054 non-null   object
 6   playerCategory    2054 non-null   object
dtypes: object(7)
memory usage: 112.5+ KB

4. Sacar medias, std, etc sobre datos de interes.

vamos a mirar la columna de rating

In [ ]:
data['rating']

0       1.53
1       1.31
2       1.31
3       1.29
4       1.26
        ...
2049    0.33
2050    0.29
2051    0.27
2052    0.19
2053    0.19
Name: rating, Length: 2054, dtype: object

In [ ]:
### como acceder a una columna
# nombre_dataframe['nombre_de_la_columna']
type(data['rating'])

pandas.core.series.Series

sera que con lo que me acabo de decir el type cumple el objetivo de saber el tipo de dato ?

In [ ]:
type(data['rating'][0])

str

vamos a asumir que mi columna de interes es rating

In [ ]:
### cambiar el tipo de dato de la columna

data['rating'] = data['rating'].astype(dtype='float')

ValueError: could not convert string to float: ''

En mi conjunto de datos encuentro que hay datos vacios

- Como puedo mejorara esos datos vacios?
- Como saber cuantos datos vacios son ?
- Sera que podriamos tener un porcentaje para ver a nivel de totalidad de datos ?

In [ ]:
### para saber los valores nulos

data.isnull().sum()

playerName          0
team                0
rating              0
region              0
playerStatistics    0
agent               0
playerCategory      0
dtype: int64

In [ ]:
data.isna().sum()

playerName          0
team                0
rating              0
region              0
playerStatistics    0
agent               0
playerCategory      0
dtype: int64

al descartar datos nulos me encuentro que tengo datos vacios

### tratamiento de datos

In [ ]:
data['rating']

0       1.53
1       1.31
2       1.31
3       1.29
4       1.26
        ...
2049    0.33
2050    0.29
2051    0.27
2052    0.19
2053    0.19
Name: rating, Length: 2054, dtype: object

In [ ]:
## debo tener columnas objetivo

mascara = data['rating'] == ''

data['resultado_booleano'] = mascara

data.head()

,playerName,team,rating,region,playerStatistics,agent,playerCategory,resultado_booleano
0,Kouf,AMB,1.53,Americas,"{'average_combat_score': '298.0', 'kill_deaths...","[reyna, kayo]",vct-challengers,False
1,nelu,63,1.31,Americas,"{'average_combat_score': '266.7', 'kill_deaths...","[viper, sova, breach]",vct-challengers,False
2,welyy,Blue,1.31,Americas,"{'average_combat_score': '240.9', 'kill_deaths...","[sova, fade, breach]",vct-challengers,False
3,ShoT_UP,TOR,1.29,Americas,"{'average_combat_score': '240.2', 'kill_deaths...","[skye, astra, killjoy]",vct-challengers,False
4,mada,NRG,1.26,Americas,"{'average_combat_score': '268.8', 'kill_deaths...","[raze, jett, reyna]",vct-challengers,False

In [ ]:
data[mascara].head()

,playerName,team,rating,region,playerStatistics,agent,playerCategory,resultado_booleano
1305,Yaobaike,65,,China,"{'average_combat_score': '199.0', 'kill_deaths...","[jett, omen]",vct-challengers,True
1306,huNter,ALG,,China,"{'average_combat_score': '116.5', 'kill_deaths...",[omen],vct-challengers,True
1307,f1cio,ZYG,,China,"{'average_combat_score': '169.2', 'kill_deaths...","[omen, killjoy]",vct-challengers,True
1308,FFs,ZYG,,China,"{'average_combat_score': '129.0', 'kill_deaths...","[sova, harbor]",vct-challengers,True
1309,slowly,ZYG,,China,"{'average_combat_score': '280.8', 'kill_deaths...","[yoru, omen]",vct-challengers,True

In [ ]:
## cuantos datos son ?

print(len(data[mascara]))

48

conclusion tenemos 48 datos vacios

yo quiero cumplir mi objetivo de cambiar el tipo de valor de la columna rating

como lo puedo hacer ?

In [ ]:
# quiero hacer el reemplazo sobre la columna

data['rating'].replace(to_replace='', value=0, inplace=True)

In [ ]:
# cuantos datos vacios tengo ?

mascara = data['rating'] == ''

data['resultado_booleano'] = mascara
print(len(data[mascara]))

0

In [ ]:
data['rating'][1306]

0

In [ ]:
data['rating'] = data['rating'].astype(dtype='float')

In [ ]:
## revisemos que si haya cambiado el tipo de valor

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2054 entries, 0 to 2053
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   playerName          2054 non-null   object
 1   team                2054 non-null   object
 2   rating              2054 non-null   float64
 3   region              2054 non-null   object
 4   playerStatistics    2054 non-null   object
 5   agent               2054 non-null   object
 6   playerCategory      2054 non-null   object
 7   resultado_booleano  2054 non-null   bool
dtypes: bool(1), float64(1), object(6)
memory usage: 114.5+ KB

In [ ]:
data.describe()

            rating
count  2054.000000
mean      0.855389
std       0.237377
min       0.000000
25%       0.750000
50%       0.890000
75%       1.010000
max       1.580000

----

### Tarea para entregar en el quiz y en la actividad asincrona.

1. cargar dataset llamado exams_data_modificado.csv
2. repetir los pasos anteriores del dataset valorant_data.json
3. El analisis se realizara sobre la columna math score

### Investiguen
1. Que es un EDA - con sus palabras realicen el paso a paso ( de forma escrita (no quiero codigo) ) - https://www.ibm.com/mx-es/topics/exploratory-data-analysis

https://codificandobits.com/blog/analisis-exploratorio-de-datos/#:~:text=En%20este%20post%20les%20comparto%20una%20gu%C3%ADa%20paso,instrucciones%20para%20descargar%20esta%20gu%C3%ADa%20en%20formato%20PDF.

**EDA:**

EDA hace referencia a el análisis de datos exploratorios por sus siglas en inglés.

Este sirve para conocer las principales características de un conjunto de datos. Nos ayuda a tener un mayor control sobre los datos y así poder observar cual es su comportamiento, también nos ayuda a saber si el análisis de datos utilizado es adecuado.

Tipos de EDA:


*   Univariante no gráfica: en este caso los datos solo tienen una variable, su objetivo es describir datos y encontrar patrones existentes.

*   Gráfico univariante: este análisis no muestra en totalidad los datos, por lo que es necesario utilziar métodos gráficos como; Diagramas de tallo y hojas, histrogramas, diagramas de caja entre otros.

*   Multivariante no gráfica: Estos datos tienen más de una variable, nos muestra la relación que hay entre las variables por medio de métodos estadísticos.

*  Gráfico multivariante: Utilizan gráficos para mostrar la relación entre dos o más conjuntos de datos. El gráfico que más se utiliza es el diagrama de barras.

Para realizar una EDA los programas más usados son:

- Python

- R


---


Para la realización de una EDA se debén tener en cuenta los siguientes pasos:



1.   Debemos saber que pregunta debemos de responder y conocer las características de nuestro dataset, observar su tamañano ver su contenido.


2. Después de ver nuestros datos debemos definir que tipos de datos tenemos, existen datos numéricos y categóricos.

  Los datos numéricos pueden ser valores enteros o decimales.

  Los datos categóricos pueden ser nominales,estos datos no se pueden ordenar ni medir, o binarios, estos datos solo nos pueden decir si los datos pertecen a un grupo o a otro y por ultimo los datos ordinales son los que se pueden ordenar.

3. Elegir un método de estadística descriptiva, estos dependera de las variables que tengamos.

  Existen dos medidas de tendencia la central y las de variabilidad.

  Las medidas de tendencia central nos muestran valores como la media, la mediana y la moda.

  Las medidas de variabilidad nos indican que tan agrupados o dispersos están los datos, para esto se usa la desviación estándar y el rango intercuartiles.

4. En el siguiente paso es interpretar los valores que nos dieron los métodos estadísticos para esto podemos utilizar métodos gráficos como el histograma o la gráfica de barras.

5. Analizar si existe alguna relación entre una o más variables.

  Podemos usar el análisis bivariado en el cual comparamos las variables, se pueden utilizar gráficas para esto.

  El otro análisis es el multivariados donde comparamos simultáneamente todas las posibles relaciones de las variables, para cada comparación se calcula el índice de correlación y se realiza una matriz de correlación con los resultados.

6. Por último debemos sacar las conclusiones de todo el análisis realizado.